name: Develop PR - build, test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        include:
          - component: Frontend
            location: ui
          - component: Backend
            location: .
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.component }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.location }}/
          file: ${{ matrix.location }}/Dockerfile
          push: false
